-- Étape 2 : schéma du clone original, à revoir avant exécution.
-- À exécuter une seule fois dans un projet sans ces tables.
-- Aucun DROP ni remplacement de table existante : transaction annulée en cas de conflit.
-- Ne crée pas encore le modèle cible topics/items/votes de l'étape 3.
begin;

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique,
  updated_at timestamptz default now()
);

create table public.subreddits (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

create table public.posts (
  id bigint generated by default as identity primary key,
  title text not null check (length(trim(title)) > 0),
  text text,
  url text,
  image_url text,
  posted_by uuid not null constraint posts_posted_by_fkey references public.profiles(id) on delete cascade,
  subreddit bigint not null references public.subreddits(id),
  created_at timestamptz not null default now()
);

create table public.post_votes (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  is_upvote boolean not null,
  created_at timestamptz not null default now(),
  unique(user_id, post_id)
);

create table public.comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  text text not null check (length(trim(text)) > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index posts_created_at_idx on public.posts(created_at desc);
create index posts_subreddit_idx on public.posts(subreddit);
create index posts_posted_by_idx on public.posts(posted_by);
create index post_votes_post_id_idx on public.post_votes(post_id);
create index comments_post_id_idx on public.comments(post_id);
create index comments_user_id_idx on public.comments(user_id);

alter table public.profiles enable row level security;
alter table public.subreddits enable row level security;
alter table public.posts enable row level security;
alter table public.post_votes enable row level security;
alter table public.comments enable row level security;

-- Lectures publiques requises par les pages et le calcul de score actuel.
create policy profiles_read on public.profiles for select to anon, authenticated using (true);
create policy subreddits_read on public.subreddits for select to anon, authenticated using (true);
create policy posts_read on public.posts for select to anon, authenticated using (true);
create policy votes_read on public.post_votes for select to anon, authenticated using (true);
create policy comments_read on public.comments for select to anon, authenticated using (true);

create policy profiles_update on public.profiles for update to authenticated
  using ((select auth.uid()) = id) with check ((select auth.uid()) = id);
create policy posts_insert on public.posts for insert to authenticated
  with check ((select auth.uid()) = posted_by);
create policy posts_delete on public.posts for delete to authenticated
  using ((select auth.uid()) = posted_by);
create policy votes_insert on public.post_votes for insert to authenticated
  with check ((select auth.uid()) = user_id);
create policy votes_update on public.post_votes for update to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy votes_delete on public.post_votes for delete to authenticated
  using ((select auth.uid()) = user_id);
create policy comments_insert on public.comments for insert to authenticated
  with check ((select auth.uid()) = user_id);
create policy comments_delete on public.comments for delete to authenticated
  using ((select auth.uid()) = user_id);

-- Privilèges explicites, limités aux opérations utilisées par l'application.
revoke all on public.profiles, public.subreddits, public.posts, public.post_votes, public.comments from anon, authenticated;
grant select on public.profiles, public.subreddits, public.posts, public.post_votes, public.comments to anon, authenticated;
grant update(username, updated_at) on public.profiles to authenticated;
grant insert, delete on public.posts, public.comments to authenticated;
grant insert, update, delete on public.post_votes to authenticated;
grant usage on sequence public.subreddits_id_seq, public.posts_id_seq, public.post_votes_id_seq, public.comments_id_seq to authenticated;

create function public.reddit_clone_handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles(id, username)
  values (new.id, nullif(trim(new.raw_user_meta_data ->> 'username'), ''));
  return new;
end;
$$;

revoke all on function public.reddit_clone_handle_new_user() from public, anon, authenticated;
create trigger reddit_clone_on_auth_user_created
  after insert on auth.users
  for each row execute function public.reddit_clone_handle_new_user();

-- Utilisateurs déjà créés : profil sans username pour éviter les collisions.
-- Le nom peut ensuite être renseigné dans /account.
insert into public.profiles(id) select id from auth.users;

-- Une communauté minimale pour rendre la création de posts utilisable.
insert into public.subreddits(name) values ('general');

notify pgrst, 'reload schema';
commit;
